### ISSUE TITLE
Providing a license 

### ISSUE THREAD

**Issue by CamDavidsonPilon** [mattytrentini/micropython-tmp1075#2]
Hey @mattytrentini - do you mind adding a license to this repo? I'd like to use it, but feel it uncomfortable without there being a license I can reference.

**Comment by mattytrentini** [comment]
Hi @CamDavidsonPilon, I've added the MIT license to the repository. Sorry, it should have been there from the beginning!

**Comment by CamDavidsonPilon** [comment]
Thanks! ❤️
